package modele.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the categorie table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="categorie"
 */
public abstract class BaseCategorie  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_ID_CATEGORIE = "id_categorie";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id_categorie;

	// fields
	private java.lang.String _nom;

	// collections
	private java.util.Set _creations;


	// constructors
	public BaseCategorie () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCategorie (java.lang.Integer _id_categorie) {
		this.setId_categorie(_id_categorie);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCategorie (
		java.lang.Integer _id_categorie,
		java.lang.String _nom) {

		this.setId_categorie(_id_categorie);
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_categorie"
     */
	public java.lang.Integer getId_categorie () {
		return _id_categorie;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id_categorie the new ID
	 */
	public void setId_categorie (java.lang.Integer _id_categorie) {
		this._id_categorie = _id_categorie;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: creations
	 */
	public java.util.Set getCreations () {
		return this._creations;
	}

	/**
	 * Set the value related to the column: creations
	 * @param _creations the creations value
	 */
	public void setCreations (java.util.Set _creations) {
		this._creations = _creations;
	}
	
	public void addToCreations (Object obj) {
		if (null == this._creations) this._creations = new java.util.HashSet();
		this._creations.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof modele.base.BaseCategorie)) return false;
		else {
			modele.base.BaseCategorie mObj = (modele.base.BaseCategorie) obj;
			if (null == this.getId_categorie() || null == mObj.getId_categorie()) return false;
			else return (this.getId_categorie().equals(mObj.getId_categorie()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId_categorie()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId_categorie().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}