package modele.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the creation table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="creation"
 */
public abstract class BaseCreation  implements Serializable {

	public static String PROP_DATE_PUBLICATION = "DatePublication";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_IMAGE = "Image";
	public static String PROP_ID_CREATION = "id_Creation";
	public static String PROP_CATEGORIE = "categorie";
	public static String PROP_DOSSIERIMAGE = "dossierimage";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id_Creation;

	// fields
	private java.util.Date _datePublication;
	private java.lang.String _description;
	private byte[] _image;

	// many to one
	private modele.DossierImage _dossierimage;
	private modele.Categorie _categorie;


	// constructors
	public BaseCreation () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCreation (java.lang.Integer _id_Creation) {
		this.setId_Creation(_id_Creation);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCreation (
		java.lang.Integer _id_Creation,
		modele.DossierImage _dossierimage,
		modele.Categorie _categorie,
		java.util.Date _datePublication) {

		this.setId_Creation(_id_Creation);
		this.setDossierimage(_dossierimage);
		this.setCategorie(_categorie);
		this.setDatePublication(_datePublication);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_Creation"
     */
	public java.lang.Integer getId_Creation () {
		return _id_Creation;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id_Creation the new ID
	 */
	public void setId_Creation (java.lang.Integer _id_Creation) {
		this._id_Creation = _id_Creation;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: date_publication
	 */
	public java.util.Date getDatePublication () {
		return _datePublication;
	}

	/**
	 * Set the value related to the column: date_publication
	 * @param _datePublication the date_publication value
	 */
	public void setDatePublication (java.util.Date _datePublication) {
		this._datePublication = _datePublication;
	}


	/**
	 * Return the value associated with the column: description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: description
	 * @param _description the description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: image
	 */
	public byte[] getImage () {
		return _image;
	}

	/**
	 * Set the value related to the column: image
	 * @param _image the image value
	 */
	public void setImage (byte[] _image) {
		this._image = _image;
	}


	/**
     * @hibernate.property
     *  column=ID_DOSSIERIMAGE
	 * not-null=true
	 */
	public modele.DossierImage getDossierimage () {
		return this._dossierimage;
	}

	/**
	 * Set the value related to the column: ID_DOSSIERIMAGE
	 * @param _dossierimage the ID_DOSSIERIMAGE value
	 */
	public void setDossierimage (modele.DossierImage _dossierimage) {
		this._dossierimage = _dossierimage;
	}


	/**
     * @hibernate.property
     *  column=id_categorie
	 * not-null=true
	 */
	public modele.Categorie getCategorie () {
		return this._categorie;
	}

	/**
	 * Set the value related to the column: id_categorie
	 * @param _categorie the id_categorie value
	 */
	public void setCategorie (modele.Categorie _categorie) {
		this._categorie = _categorie;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof modele.base.BaseCreation)) return false;
		else {
			modele.base.BaseCreation mObj = (modele.base.BaseCreation) obj;
			if (null == this.getId_Creation() || null == mObj.getId_Creation()) return false;
			else return (this.getId_Creation().equals(mObj.getId_Creation()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId_Creation()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId_Creation().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}