package modele.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the extension table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="extension"
 */
public abstract class BaseExtension  implements Serializable {

	public static String PROP_EXTENSION = "extension";
	public static String PROP_ID_EXTENSION = "idExtension";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.String _idExtension;

	// fields
	private java.lang.String _extension;


	// constructors
	public BaseExtension () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseExtension (java.lang.String _idExtension) {
		this.setIdExtension(_idExtension);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseExtension (
		java.lang.String _idExtension,
		java.lang.String _extension) {

		this.setIdExtension(_idExtension);
		this.setExtension(_extension);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_extension"
     */
	public java.lang.String getIdExtension () {
		return _idExtension;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idExtension the new ID
	 */
	public void setIdExtension (java.lang.String _idExtension) {
		this._idExtension = _idExtension;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: extension
	 */
	public java.lang.String getExtension () {
		return _extension;
	}

	/**
	 * Set the value related to the column: extension
	 * @param _extension the extension value
	 */
	public void setExtension (java.lang.String _extension) {
		this._extension = _extension;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof modele.base.BaseExtension)) return false;
		else {
			modele.base.BaseExtension mObj = (modele.base.BaseExtension) obj;
			if (null == this.getIdExtension() || null == mObj.getIdExtension()) return false;
			else return (this.getIdExtension().equals(mObj.getIdExtension()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdExtension()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdExtension().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}